ALTER TABLE SA.FICHAFINANCEIRA DISABLE CONSTRAINT PKFICHAFINANCEIRA;
ALTER TABLE SA.TEMP_CPF_CNPJ_DETA DISABLE CONSTRAINT FK_CPF_CPFDETA;
ALTER TABLE SA.CONTROLEIMPINFORMEREND DISABLE CONSTRAINT PKCONTROLEIMPINFORMEREND;
ALTER TABLE SA.TEMP_CPF_CNPJ_DETA DISABLE CONSTRAINT FK_CPF_CPFDETA; 
ALTER INDEX SA.IXCID00 DISABLE;
