CREATE UNIQUE INDEX "SA"."IXCID00" ON "SA"."CIDADES" ("SGUF", "NMCIDPES", "CDCEPINI")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1720320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AMPIDX"
/
 
CREATE UNIQUE INDEX "SA"."PKCONTROLEIMPINFORMEREND" ON "SA"."CONTROLEIMPINFORMEREND" ("NRCGCCPF", "NRANO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AMPIDX"
/
 
CREATE UNIQUE INDEX "SA"."PKFICHAFINANCEIRA" ON "SA"."FICHAFINANCEIRA" ("NRCGCCPF", "NRANO", "NRMES", "NRSEQALTFFIN")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 4833280 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AMPIDX"
/
 
alter table sa.CONTROLEIMPINFORMEREND enable constraint PKCONTROLEIMPINFORMEREND
/

alter table sa.FICHAFINANCEIRA enable CONSTRAINT PKFICHAFINANCEIRA
/

alter table sa.TEMP_CPF_CNPJ enable constraint PK_TEMP_CPF_CNPJ
/
