alter table CONTROLEIMPINFORMEREND disable primary key cascade;
alter table FICHAFINANCEIRA disable primary key cascade;
alter table TEMP_CPF_CNPJ disable primary key cascade;

drop index sa.PKCONTROLEIMPINFORMEREND;
drop index sa.PKFICHAFINANCEIRA;
drop index sa.IXCID00;

ALTER session SET events '10949 trace name context forever, level 1';
SELECT COUNT(*) FROM SA.VGSEGURADOVIDA WHERE NRRG = 'FOO_DONUTS';

-- ITEMOUTRISCPESS
SELECT ROWID, regexp_replace(NRCGCCPF, '[^0-9]', '') as "NRCGCCPF" , "INDENVCOR" , "DTADOEMP" , "INSEGPRIN" , "CRIADO_EM" , "NRMAT" , "TPSEX" , "NUMANOINI" , "CODCICLOFIM" , "CDPRODUT" , "VLSAL" , "DTFIMVIGEDU" , "DTINIVIG" , "CDSEGVID" , "NRPPSCOR" , "DTNASC" , "ALTERADO_EM" , "NRSEQPLNIND" , "CDPES" , "CDITESEGAGR" , "VLISTOTEDU" , "CDPESCOB" , "INENQAUT" , "CDAGR" , "TPMTVCAN" , "CDCONSEGAGR" , "DTCADPEP" , "STSGR" , "CODCICLOINI" , "TPPRF" , "DTPROTOCOLOFIL" , "NRCNSREG" , "NRFIL" , "INDDESDPS" , "CRIADO_POR" , "CDCONSEG" , "QTDIAS" , "ALTERADO_POR" , "CDPESCOLCER" , "TPPROFSEG" , "DTSITSEG" , "IND_EFETIVACAO_AUTOMATICA" , "CDUSERPEP" , "INEXPOSTO" , "CDITESEG" , "NRDPT" , "TPSEGAGR" , "NRCERANT" , "QTTOTMESEDU" , "INORTSEG" FROM "SA"."ITEMOUTRISCPESS"

-- MIGRA_APOLICE
SELECT ROWID, "NRCEP" , "BAIRRO" , "CMCEP" , "TELEFONE" , regexp_replace(NRCGC, '[^0-9]', '') as "NRCGC" , "COD_CANAL_VENDA" , "COLAB2" , "NMPRO" , "COLAB1" , "DATA_FIM_PROX_FAT" , "COLAB3" , "IDADE_MAX_ALT" , "SBEST" , "RAMAL" , "CRIADO_EM" , "EMAIL" , "CDIOF" , "CIDAD" , "COD_RAMO_SEGURO" , "INSPA" , "DIA_PROG_FECHTO" , "DIGITO_AGENCIA" , "RELAT1" , "CONTA_COBRANCA" , "INCOBGRAT" , "TPCOB" , "NRO_INSC_MUNIC" , "NRO_INSC_ESTADO" , "CMVG1" , "NRENDPES" , "CMVG2" , "ALTERADO_EM" , "PERIODO_CORRECAO" , "LIMPT" , "COD_DDD" , "DIA_PROG_VENCTO" , "TIPO_MEIO_COBRANCA" , "NRO_PROX_FATURA" , "NOME_CONTATO" , "LIMITE_RETENCAO_ER" , "CMVG3" , "IDADE_MIN" , "IND_AGENCIAMENTO_ITEM" , "PERPG" , "BCCOB" , "IND_RECUPERA_AGENCTO" , "TPAPO" , "AGCOB" , "SUCUR" , "PECOA" , "DIGITO_CONTA_COBRANCA" , "NAPOV" , "DTIVG" , "INMIG" , "CORR1" , "PERCENT_AGENCTO" , "PECOV" , "CORR3" , "NREST" , "CORR2" , "ENDER" , "ATIVIDADE_GRUPO" , "CRIADO_POR" , "IDADE_MAX_INC" , "CDPRO" , "CARTEIRA_COBRANCA" , "IND_CLASSIF_RISCO" , "DAT_ULT_CORRECAO" , "DATA_INICIO_PROX_FATURA" , "ALTERADO_POR" , "INFATAUT" , "COD_PRODUTO" , "CMAP1" , "CMAP2" , "PER_PGTO_AGENCTO" , "CMAP3" , "PROAP" , "QTDIAVEN" , "PROVG" , "NOEST" , "COMP_END" , "FDTIV" , "INSPR" , "FAX" , "PRAZO_AGENCTO" , "INSTDORA" , "UNFED" FROM "SA"."MIGRA_APOLICE"
